services:
  - type: web
    name: waqf-whatsapp-service
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3001
      - key: ALLOWED_ORIGINS
        value: https://abdarhemsheet-max.github.io,http://localhost:5173
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: true
